# Generated by Django 5.1.1 on 2024-09-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.FloatField(blank=True, db_column='Valor', null=True)),
                ('datahora', models.DateTimeField(blank=True, db_column='DataHora', null=True)),
                ('nome_vendedor', models.CharField(blank=True, db_column='Nome_Vendedor', max_length=35, null=True)),
                ('nome_fabricante', models.CharField(blank=True, db_column='Nome_Fabricante', max_length=50, null=True)),
                ('quantidade_vendida', models.IntegerField(blank=True, db_column='Quantidade_Vendida', null=True)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=35, null=True)),
                ('cliente', models.CharField(blank=True, db_column='Cliente', max_length=50, null=True)),
                ('status', models.IntegerField()),
                ('adm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'venda',
                'managed': False,
            },
        ),
    ]
