# Generated by Django 5.1 on 2024-09-06 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
