# Generated by Django 5.1.1 on 2024-09-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField(blank=True, null=True)),
                ('qtd_vendida', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_venda',
                'managed': False,
            },
        ),
    ]
